src/Entity/Performance.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PerformanceRepository")
 */
class Performance
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Artist", inversedBy="performances")
     * @ORM\JoinColumn(nullable=false)
     */
    private $artist;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\Column(type="time")
     */
    private $commencement;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $hall;

    /**
     * @ORM\Column(type="integer")
     */
    private $max_seats;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getArtist(): ?Artist
    {
        return $this->artist;
    }

    public function setArtist(?Artist $artist): self
    {
        $this->artist = $artist;

        return $this;
    }

    public function getDate(): ?string
    {
        return $this->date->format("d-m-Y");
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getCommencement(): ?string
    {
        return $this->commencement->format("H:i");
    }

    public function setCommencement(\DateTimeInterface $commencement): self
    {
        $this->commencement = $commencement;

        return $this;
    }

    public function getHall(): ?string
    {
        return $this->hall;
    }

    public function setHall(string $hall): self
    {
        $this->hall = $hall;

        return $this;
    }

    public function getMaxSeats(): ?int
    {
        return $this->max_seats;
    }

    public function setMaxSeats(int $max_seats): self
    {
        $this->max_seats = $max_seats;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }
}

src/Form/PerformanceType.php
<?php

namespace App\Form;

use App\Entity\Performance;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PerformanceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('date')
            ->add('commencement')
            ->add('hall')
            ->add('max_seats')
            ->add('price')
            ->add('artist')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Performance::class,
        ]);
    }
}

src/Controller/PerformanceController.php
<?php

namespace App\Controller;

use App\Entity\Performance;
use App\Form\PerformanceType;
use App\Repository\PerformanceRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\DateTime;


/**
 * @Route("/performance")
 */
class PerformanceController extends AbstractController
{
    /**
     * @Route("/", name="performance_index", methods={"GET"})
     */
    public function index(PerformanceRepository $performanceRepository): Response
    {
        return $this->render('performance/index.html.twig', [
            'performances' => $performanceRepository->getByPeriodPerformances(new DateTime("+1 week"), new DateTime()),
        ]);
    }

    /**
     * @Route("/new", name="performance_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $performance = new Performance();
        $form = $this->createForm(PerformanceType::class, $performance);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($performance);
            $entityManager->flush();

            return $this->redirectToRoute('performance_index');
        }

        return $this->render('performance/new.html.twig', [
            'performance' => $performance,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="performance_show", methods={"GET"})
     */
    public function show(Performance $performance): Response
    {
        return $this->render('performance/show.html.twig', [
            'performance' => $performance,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="performance_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Performance $performance): Response
    {
        $form = $this->createForm(PerformanceType::class, $performance);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('performance_index');
        }

        return $this->render('performance/edit.html.twig', [
            'performance' => $performance,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="performance_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Performance $performance): Response
    {
        if ($this->isCsrfTokenValid('delete'.$performance->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($performance);
            $entityManager->flush();
        }

        return $this->redirectToRoute('performance_index');
    }
}

templates/performance/_delete_form.html.twig
<form method="post" action="{{ path('performance_delete', {'id': performance.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ performance.id) }}">
    <button class="btn">Delete</button>
</form>

templates/performance/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/performance/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Performance{% endblock %}

{% block body %}
    <h1>Edit Performance</h1>

    {{ include('performance/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('performance_index') }}">back to list</a>

    {{ include('performance/_delete_form.html.twig') }}
{% endblock %}

templates/performance/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Performance index{% endblock %}

{% block body %}
    <h1>Performance index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date</th>
                <th>Commencement</th>
                <th>Hall</th>
                <th>Max_seats</th>
                <th>Price</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for performance in performances %}
            <tr>
                <td>{{ performance.id }}</td>
                <td>{{ performance.date ? performance.date|date('Y-m-d') : '' }}</td>
                <td>{{ performance.commencement ? performance.commencement|date('H:i:s') : '' }}</td>
                <td>{{ performance.hall }}</td>
                <td>{{ performance.maxSeats }}</td>
                <td>{{ performance.price }}</td>
                <td>
                    <a href="{{ path('performance_show', {'id': performance.id}) }}">show</a>
                    <a href="{{ path('performance_edit', {'id': performance.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('performance_new') }}">Create new</a>
{% endblock %}

templates/performance/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Performance{% endblock %}

{% block body %}
    <h1>Create new Performance</h1>

    {{ include('performance/_form.html.twig') }}

    <a href="{{ path('performance_index') }}">back to list</a>
{% endblock %}

templates/performance/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Performance{% endblock %}

{% block body %}
    <h1>Performance</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ performance.id }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ performance.date ? performance.date|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Commencement</th>
                <td>{{ performance.commencement ? performance.commencement|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Hall</th>
                <td>{{ performance.hall }}</td>
            </tr>
            <tr>
                <th>Max_seats</th>
                <td>{{ performance.maxSeats }}</td>
            </tr>
            <tr>
                <th>Price</th>
                <td>{{ performance.price }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('performance_index') }}">back to list</a>

    <a href="{{ path('performance_edit', {'id': performance.id}) }}">edit</a>

    {{ include('performance/_delete_form.html.twig') }}
{% endblock %}